[package]
name = "raytracer"
version = "0.1.0"
edition = "2021"

[dependencies]
approx = "0.5.1"
clap = { version = "4.5.17", features = ["derive"] }
png = "0.17.13"
quick-xml = "0.36.1"
rand = "0.8.5"
rayon = "1.10.0"
threadpool = "1.8.1"
threadpool_scope = "0.1.0"
